server:
  port: 90
spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    hikari:
      username: root
      password: 123
  redis:
    # redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 6000
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.space.mybatisrediscache.bo
  configuration:
    cache-enabled: true
